id = "litejs"
name = "LiteJS"
description = "LiteJS UI template support for Zed"
version = "26.2.1"
authors = ["Lauri Rooden"]
schema_version = 1
repository = "https://github.com/litejs/tree-sitter-litejs"

[grammars.litejs]
repository = "https://github.com/litejs/tree-sitter-litejs"
rev = "main"
